services:
  db:
    image: postgres:15
    container_name: seniorCare_db_Spring
    restart: always
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: SeniorCare
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: seniorCare_redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  app:
    build:
      context: .
    container_name: seniorCare_spring
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - '8080:8080'
    environment:
      SPRING_PROFILES_ACTIVE: docker

volumes:
  pgdata:
    driver: local
  redis_data:
    driver: local