server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://db:5432/SeniorCare
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
    placeholder-replacement: false
  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379

azure:
  speech:
    subscription-key: ${AZURE_SPEECH_KEY}
    region: ${AZURE_SPEECH_REGION}

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 86400000

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5435/SeniorCare
  data:
    redis:
      host: localhost
      port: 6379